repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        exclude: ^tests/

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, pep8-naming]
        args: [--max-line-length=131]

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
        args: ["--disable=C0301,C0116,E0401,C0103"]
